name: whatschat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  go_router: ^12.1.0
  intl: ^0.18.0
  phone_form_field: ^8.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.5
  url_launcher_platform_interface: ^2.1.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
